//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGBAFrameWork {
	using System;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonGBAFrameWork.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca una cadena traducida similar a /*
		///Note: both image and palette should be LZ77 compressed!
		///Table format: [image pointer][pal pointer]..........
		///*/
		///.equiv table_location, 0xPOINTERTABLE
		///.thumb
		///push {r4-r5, lr}
		///sub sp, sp, #0x18
		///ldr r0, =0x20370C0
		///ldrh r0, [r0, #2]
		///mov r1, #0
		///mov r2, #0x14
		///mul r2, r0
		///mov r3, #4
		///mov r0, #10
		///str r0, [sp]
		///str r0, [sp, #4]
		///mov r0, #0xD
		///str r0, [sp, #8]
		///mov r0, #0x40
		///str r0, [sp, #0xC]
		///add r0, sp, #0x10
		///ldr r4, =0x810FE51
		///bl bx_r4
		///add r0, sp, #0x10
		///ldr r4, =0x8003CE5
		///bl bx_r4
		///ldr r4, = [resto de la cadena truncado]&quot;;.
		/// </summary>
		internal static string ASMMugshotsFRMake {
			get {
				return ResourceManager.GetString("ASMMugshotsFRMake", resourceCulture);
			}
		}
	}
}
