//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGBAFrameWork.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonGBAFrameWork.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .thumb
        ///@ 00 49 08 47 XX XX XX XX at x137134
        ///
        ///ldr r1, [r2]
        ///ldrb r2,[r1,#4]
        ///add r2,#0x32
        ///lsl r2,r2,#0x18
        ///lsr r2,r2,#0x18
        ///push {r0-r3}
        ///ldr r0, =(0x0203B140)
        ///ldr r0, [r0]
        ///ldr r2, =(0x3290)
        ///add r0, r0, r2
        ///mov r1, #0
        ///bl decryptbranch
        ///bl getnaturebranch
        ///cmp r0, #1 @ Lonely
        ///beq red
        ///cmp r0, #2 @ Brave
        ///beq red
        ///cmp r0, #3 @ Adamant
        ///beq red
        ///cmp r0, #4 @ Naughty
        ///beq red
        ///cmp r0, #5 @ Bold
        ///beq blue
        ///cmp r0, #10 @ Timid
        ///beq blue
        ///cmp r0, #15 @ Modest
        ///beq blue
        ///cmp r0, #20 @ Calm
        ///beq blue
        ///
        ///blac [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ColorearStats_Ataque_FR {
            get {
                return ResourceManager.GetString("ColorearStats_Ataque_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .thumb
        ///@ 00 49 08 47 XX XX XX XX at x13717C
        ///
        ///mov r2,r8
        ///ldr r1, [r2]
        ///ldrb r2,[r1,#8]
        ///add r2,#0x32
        ///lsl r2,r2,#0x18
        ///lsr r2,r2,#0x18
        ///push {r0-r3}
        ///ldr r0, =(0x0203B140)
        ///ldr r0, [r0]
        ///ldr r2, =(0x3290)
        ///add r0, r0, r2
        ///mov r1, #0
        ///bl decryptbranch
        ///bl getnaturebranch
        ///cmp r0, #3 @ Adamant
        ///beq blue
        ///cmp r0, #8 @ Impish
        ///beq blue
        ///cmp r0, #13 @ Jolly
        ///beq blue
        ///cmp r0, #15 @ Modest
        ///beq red
        ///cmp r0, #16 @ Mild
        ///beq red
        ///cmp r0, #17 @ Quiet
        ///beq red
        ///cmp r0, #19 @ Rash
        ///beq red
        ///cmp r0, #23 @ Careful
        ///be [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ColorearStats_AtaqueEspecial_FR {
            get {
                return ResourceManager.GetString("ColorearStats_AtaqueEspecial_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .thumb
        ///@ 00 49 08 47 XX XX XX XX at x137158
        ///
        ///ldr r1, [r2]
        ///ldrb r2,[r1,#6]
        ///add r2,#0x32
        ///lsl r2,r2,#0x18
        ///lsr r2,r2,#0x18
        ///push {r0-r3}
        ///ldr r0, =(0x0203B140)
        ///ldr r0, [r0]
        ///ldr r2, =(0x3290)
        ///add r0, r0, r2
        ///mov r1, #0
        ///bl decryptbranch
        ///bl getnaturebranch
        ///cmp r0, #1 @ Lonely
        ///beq blue
        ///cmp r0, #5 @ Nold
        ///beq red
        ///cmp r0, #7 @ Relaxed
        ///beq red
        ///cmp r0, #8 @ Impish
        ///beq red
        ///cmp r0, #9 @ Lax
        ///beq red
        ///cmp r0, #11 @ Hasty
        ///beq blue
        ///cmp r0, #16 @ Mild
        ///beq blue
        ///cmp r0, #21 @ Gentle
        ///beq blue
        ///
        ///black:        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ColorearStats_Defensa_FR {
            get {
                return ResourceManager.GetString("ColorearStats_Defensa_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .thumb
        ///@ 00 49 08 47 XX XX XX XX at x1371A4
        ///
        ///ldr r1, [r2]
        ///ldrb r2,[r1,#0xA]
        ///add r2,#0x32
        ///lsl r2,r2,#0x18
        ///lsr r2,r2,#0x18
        ///push {r0-r3}
        ///ldr r0, =(0x0203B140)
        ///ldr r0, [r0]
        ///ldr r2, =(0x3290)
        ///add r0, r0, r2
        ///mov r1, #0
        ///bl decryptbranch
        ///bl getnaturebranch
        ///cmp r0, #4 @ Naughty
        ///beq blue
        ///cmp r0, #9 @ Lax
        ///beq blue
        ///cmp r0, #14 @ Naive
        ///beq blue
        ///cmp r0, #19 @ Rash
        ///beq blue
        ///cmp r0, #20 @ Calm
        ///beq red
        ///cmp r0, #21 @ Gentle
        ///beq red
        ///cmp r0, #22 @ Sassy
        ///beq red
        ///cmp r0, #23 @ Careful
        ///beq red
        ///
        ///bl [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ColorearStats_DefensaEspecial_FR {
            get {
                return ResourceManager.GetString("ColorearStats_DefensaEspecial_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .text
        ///.thumb
        ///.thumb_func
        ///.align 2
        ///
        ///main:
        ///    push {r5}
        ///    sub sp, sp, #0x20
        ///    ldr r0, [r4] @pokemon summary pointer
        ///    add r0, #0xA3 @poke nature
        ///    ldrb r1, [r0]
        ///    ldr r0, nature_stat_table
        ///    lsl r2, r1, #2
        ///    add r2, r1, r2 @multiply by 5
        ///    add r2, r2, r0 @r2 contains nature info
        ///    ldr r3, left_stats_string
        ///    mov r1, sp
        ///    mov r5, #0
        ///    
        ///handle_hp:
        ///    ldrb r0, [r3, r5]
        ///    strb r0, [r1, r5]
        ///    add r5, #1
        ///    cmp r5, #6
        ///    bne handle_hp
        ///    add r3, #6
        ///    add  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ColorearStats_LeftStats_Esmeralda {
            get {
                return ResourceManager.GetString("ColorearStats_LeftStats_Esmeralda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .thumb
        ///@ 00 49 08 47 XX XX XX XX at 081371F0
        ///
        ///ldr r1, [r2]
        ///ldrb r2,[r1,#0xE]
        ///add r2,#0xF
        ///lsl r2,r2,#0x18
        ///lsr r2,r2,#0x18
        ///ldr r6, blackfont
        ///ldr r1, =(0xOFFSET4+1)
        ///bx r1
        ///
        ///.align 2
        ///blackfont: .word 0x08NNNNNN @ In a vanilla FR ROM, this contains: 00 0E 0A 00.
        /// </summary>
        internal static string ColorearStats_RevertirColorANegro_FR {
            get {
                return ResourceManager.GetString("ColorearStats_RevertirColorANegro_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .text
        ///.thumb
        ///.thumb_func
        ///.align 2
        ///
        ///main:
        ///    push {r5}
        ///    sub sp, sp, #0x20
        ///    ldr r0, [r4] @pokemon summary pointer
        ///    add r0, #0xA3 @poke nature
        ///    ldrb r1, [r0]
        ///    ldr r0, nature_stat_table
        ///    lsl r2, r1, #2
        ///    add r2, r1, r2 @multiply by 5
        ///    add r2, r2, r0 @r2 contains nature info
        ///    add r2, #3 @r2 contains beg of spatk stat
        ///    ldr r3, right_stats_string
        ///    mov r1, sp
        ///    mov r5, #0
        ///
        ///handle_spatk:
        ///    ldrb r0, [r2]
        ///    cmp r0, #1
        ///    beq red_font_spatk
        ///    cmp r0, #0x [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ColorearStats_RightStats_Esmeralda {
            get {
                return ResourceManager.GetString("ColorearStats_RightStats_Esmeralda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .thumb
        ///@ 00 49 08 47 XX XX XX XX at x1371C8
        ///
        ///mov r2,r8
        ///ldr r1, [r2]
        ///ldrb r2,[r1,#0xC]
        ///add r2,#0x32
        ///lsl r2,r2,#0x18
        ///lsr r2,r2,#0x18
        ///push {r0-r3}
        ///ldr r0, =(0x0203B140)
        ///ldr r0, [r0]
        ///ldr r2, =(0x3290)
        ///add r0, r0, r2
        ///mov r1, #0
        ///bl decryptbranch
        ///bl getnaturebranch
        ///cmp r0, #2 @ Brave
        ///beq blue
        ///cmp r0, #7 @ Relaxed
        ///beq blue
        ///cmp r0, #10 @ Timid
        ///beq red
        ///cmp r0, #11 @ Hasty
        ///beq red
        ///cmp r0, #13 @ Jolly
        ///beq red
        ///cmp r0, #14 @ Naive
        ///beq red
        ///cmp r0, #17 @ Quiet
        ///beq blue
        ///cmp r0, #22 @ Sassy
        ///be [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ColorearStats_Velocidad_FR {
            get {
                return ResourceManager.GetString("ColorearStats_Velocidad_FR", resourceCulture);
            }
        }
    }
}
